config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  
  get '/tasks_today', to: 'tasks#today', as: 'today_tasks'
  get '/tasks_completed', to: 'tasks#completed', as: 'completed_tasks'
  get '/tasks_overdue', to: 'tasks#overdue', as: 'overdue_tasks'
  get '/tasks_upcoming', to: 'tasks#upcoming', as: 'upcoming_tasks'

  resources :categories do 
    resources :tasks, shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user

  scope :today, -> { where(due_date: Date.current...(Date.current + 1), completed: false )}
  scope :overdue, -> { where("due_date < ? AND completed = ?", Date.current, false).order(due_date: :asc) }
  scope :completed, -> { where(completed: true) }
  scope :upcoming, -> {where(due_date: (Date.current + 1)..(Date.current + 2.weeks), completed: false).order(due_date: :asc)}

  validates :name, presence: true
  validates :description, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:index, :show, :new, :edit]
  
  def index
  end

  def show
    user_not_authorized(@category)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: "Yay! You've taken the first step towards productivity by successfully creating a category! 🥳"
    else
      render :new
    end
  end

  def edit
    user_not_authorized(@category)
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Way to go! You've boosted productivity by editing a category! 🫰"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Awesome! You've made a decisive move in boosting productivity by successfully deleting a category! 🤟"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def user_not_authorized(category)
    unless category.user == current_user
      redirect_to categories_path, alert: "Oops! The category doesn't exist from your list. 👻"
    end
  end

  def set_categories
    @categories = current_user.categories
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if user_signed_in?
      redirect_to categories_path
    else
      render :index
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, only: [:new, :create]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_categories # for the side nav

  def show
    user_not_authorized(@task)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.category = @category

    if @task.save
      redirect_to category_path(@category), notice: "Whoopee! You've just created a new task! 🎉"
    else
      render :new
    end
  end

  def edit
    user_not_authorized(@task)
  end

  def update
    if @task.update(task_params)
      redirect_to category_path(@task.category), notice: "You've boosted productivity by editing your task! 🙌"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to category_path(@task.category), notice: "Awesome! You've made a decisive move in boosting productivity by successfully deleting a task! 🤟"
  end

  def today
    @tasks_today = current_user.tasks.today
  end

  def completed
    @tasks_completed = current_user.tasks.completed
  end

  def overdue
    @tasks_overdue = current_user.tasks.overdue
  end

  def upcoming
    @tasks_upcoming = current_user.tasks.upcoming
  end


  private

  def task_params
    params.require(:task).permit(:name, :description, :due_date, :completed)
  end

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def user_not_authorized(task)
    unless task.user == current_user
      redirect_to categories_path, alert: "Oops! The task you're trying to access doesn't exist from you list. 👻"
    end
  end

  def set_categories
    @categories = current_user.categories
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(datetime)
    datetime.strftime("%b %d %I:%M%P") unless datetime.nil?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<br />

<%= form_with(model: category) do |form| %>
    <p>
        <%= form.text_field :name, placeholder: "Enter Category Name (maximum of 50 characters)" %>
    </p>

    <div class="button">
        <%= form.submit "Submit" %>
    </div> <br>

<% end %>

app/views/categories/edit.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  
  <div class="main-container">

    <h1>Edit Category</h1>

    <%= render 'form', category: @category %>

    <br />
    
    <div class="back-container">
      <div class="bck-btn">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-chevron-left fa-xl"></i>
        <% end %>
      </div>
    </div>

  </div>
  
</div>

app/views/categories/index.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  
  <div class="main-container">

      <h1>🎯 My Plans</h1><br />
      <p class="add">
        <%= link_to new_category_path, class: "add-link" do %>
          <i class="fa-solid fa-plus" style="color: #ff8787;"></i>
          <span class="add-text" style="color: #76453B;">Add Category</span>
        <% end %>
      </p> <br />

      <div class="table-container">
        <table class="table">
          <tbody>
            <% if @categories.any? %>
              <% @categories.each do |category| %>
                <tr class="table-row">
                  <td class="task-name">
                    <strong><i class="fa-solid fa-hashtag" style="color: #9c9fa5;"></i><%= link_to category.name, category_path(category), style: "color: #944E63;" %></strong>
                  </td>

                  <td class="task-btn">
                    <%= link_to new_category_task_path(category) do %> 
                      <span class="add-text"><i class="fa-solid fa-plus" style="color: #ff8787;"></i></span>
                    <% end %>
                  </td>

                  <td class="task-btn">
                    <%= link_to edit_category_path(category) do %> 
                      <i class="fa-solid fa-pen" style="color: #43766C;"></i>
                    <% end %>
                  </td>

                  <td class="task-btn">  
                    <%= button_to category_path(category), method: :delete, onclick: "return confirm('Are you sure?');", class: "del-btn" do %>
                      <i class="fa-solid fa-trash-can" style="color: rgb(90, 5, 5);"></i>
                    <% end %>
                  </td>

                  </span>

                </tr>
              <% end %>
            <% else %>
              <tr>
                <br />
                <td colspan="2">Add a category to start your productivity! </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>


      <br>  

    
  </div>
</div>

app/views/categories/new.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  <div class="main-container">

    <h1> New Category </h1>
    <%= render "form", category: @category %>

    <br />

    <div class="back-container">
      <div class="bck-btn">
        <%= link_to categories_path do %>
          <i class="fa-solid fa-chevron-left fa-xl"></i>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<%= render "layouts/navbar" %>
<div class="spacing">
  <div class="main-container">
  
    <h1> <%= @category.name %> </h1>
    <p class="transparent-text"> Created: <%= format_datetime(@category.created_at) %> </p><br />

    <div class ="add">
      <%= link_to new_category_task_path(@category), class: "add-link" do %>
        <i class="fa-solid fa-plus" style="color: #ff8787;"></i>
        <span class="add-text" style="color: #76453B;">Add Task</span>
      <% end %>
    </div>

    <p>
      <div class="table-container">
        <table class="table">
          <tbody>
            <% if @category.tasks.any? %>
              <% @category.tasks.each do |task| %>
                <tr class="table-row">
                  <td class="task-btn">
                    <%= form_with model: task, method: :patch, url: task_path(task.id) do |form| %>
                      <%= form.check_box :completed, onchange: "this.form.submit()" %>
                    <% end %>
                  </td>

                  <td class="task-name">
                    <%= task.name %>
                    <p class="desc">
                      <% if task.description.present? || task.due_date.present? %>
                        <% if task.description.present? %>
                          <i class="fa-regular fa-note-sticky"></i> <%= task.description %>
                        <% end %>

                        <% if task.due_date.present? %>
                          <i class="fa-regular fa-calendar"></i> <%= format_datetime(task.due_date) %>
                        <% end %>
                      <% end %>
                    </p>
                  </td>

                  <td class="task-btn">
                    <%= link_to edit_task_path(task) do %> 
                      <i class="fa-solid fa-pen" style="color: #43766C;"></i>
                    <% end %>
                  </td>

                  <td class="task-btn">  
                    <%= button_to task_path(task), method: :delete, onclick: "return confirm('Are you sure?');", class: "del-btn" do %>
                      <i class="fa-solid fa-trash-can" style="color: rgb(90, 5, 5);"></i>
                    <% end %>
                  </td>

                  <td class="task-btn">
                    <%= link_to task_path(task) do %>
                      <i class="fa-solid fa-ellipsis-vertical" style="color: #43766C;"></i>
                    <% end %>
                  </td>

                </tr>
              <% end %>
            <% else %>
              <tr>
                <br>
                <td colspan="2">Add task to start your productivity! </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>


    </p>
    <br />

  </div>
</div>

app/views/home/index.html.erb
<nav id="header">
    <%= image_tag('logo.png', class: 'logo') %>
    <ul class="topnav">
      <li class="topnav-li"><a href="#">Features</a></li>
      <li class="topnav-li"><a href="#">Resources</a></li>
      <li class="topnav-li"><a href="#">Pricing</a></li>
      <li class="topnav-li"><span class="login"><%= link_to "Log in", new_user_session_path %></span></li>
    </ul>
</nav>

<div class="home">
  <p class="title">
    <h2 class="">Efficiently organize your<p> work and life, finally.</p></h2>
    <h4>Become focused, organized, and calm with MinimaList.<p>Your go-to journal and planning app. </p></h4>
  </p>

  <p class="button">
    <span><%= link_to "Get Started", new_user_registration_path %></span>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="side-nav">
      
  <ul class="side-ul">
    <p class="nav-title">
      <i class="fa-solid fa-circle-user fa-xl fa-nav" style="color: #c587ae;"></i>
      <%= current_user.email %>
    </p>
    <li class="side-li">
        <span class="pin-and-link">
          <span class="emoji-pin">
            <i class="fa-solid fa-plus fa-nav" style="color: #e3008c;"></i>
          </span>
          <%= link_to "Add Category", new_category_path %>
        </span>
    </li>

    <li class="side-li">
      <span class="pin-and-link">
        <span class="emoji-pin">
          <i class="fa-solid fa-calendar-day fa-nav" style="color: #e3008c;"></i>
        </span>
        <%= link_to "Today", today_tasks_path %>
      </span>
    </li>

    <li class="side-li">
      <span class="pin-and-link">
        <span class="emoji-pin">
          <i class="fa-solid fa-calendar-week" style="color: #e3008c;"></i>
        </span>
        <%= link_to "Upcoming", upcoming_tasks_path %>
      </span>
    </li>

    <li class="side-li">
      <span class="pin-and-link">
        <span class="emoji-pin">
          <i class="fa-solid fa-calendar-check" style="color: #e3008c;"></i>
        </span>
        <%= link_to "Completed", completed_tasks_path %>
      </span>
    </li>

    <li class="side-li">
      <span class="pin-and-link">
        <span class="emoji-pin">
          <i class="fa-solid fa-calendar-xmark" style="color: #e3008c;"></i>
        </span>
        <%= link_to "Overdue", overdue_tasks_path %>
      </span>
    </li>

    <br />
    <p class="nav-title"><strong><%= link_to "My Plans", categories_path, class: "link", style: "color: #944E63;" %> </strong></p>
    <% if @categories %>
      <% @categories.each do |category| %>
        <li class="side-li">

          <span class="pin-and-link">
            <span class="emoji-pin">📌</span>
            <%= link_to truncate(category.name, length: 20), category_path(category) %> 
          </span>

        </li>
      <% end %>
    <% end %>

    <li class="side-button"><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "signout" %></li>
  </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>minimalist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path('favicon-32x32.png') %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>

  </body>
</html>

app/views/tasks/_task_common.html.erb
<br />
<div class="table-container">
  <table class="table">
    <tbody>
      <tr class="table-row">

        <td class="task-btn">
          <%= form_with model: task, method: :patch, url: task_path(task.id) do |form| %>
            <%= form.check_box :completed, onchange: "this.form.submit()" %>
          <% end %>
        </td>
        
        <td class="task-name">
          <%= task.name %>
          <p class="desc">
            <% if task.description.present? %>
                <i class="fa-regular fa-note-sticky"></i> <%= task.description %>
              <% end %>

              <% if task.due_date.present? %>
                <i class="fa-regular fa-calendar"></i> <%= format_datetime(task.due_date) %>
              <% end %>
          </p>
        </td>

        <td class="task-btn">
          <%= link_to edit_task_path(task) do %>
            <i class="fa-solid fa-pen" style="color: #43766C;"></i>
          <% end %>
        </td>

        <td class="task-btn">
          <%= button_to task_path(task), method: :delete, onclick: "return confirm('Are you sure?');", class: "del-btn" do %>
            <i class="fa-solid fa-trash-can" style="color: rgb(90, 5, 5);"></i>
          <% end %>
        </td>

        <td class="task-btn">
          <%= link_to task_path(task) do %>
            <i class="fa-solid fa-ellipsis-vertical" style="color: #43766C;"></i>
          <% end %>
        </td>

      </tr>
    </tbody>
  </table>
</div>

app/views/tasks/_task_form.html.erb
<%= form_for([@category, task]) do |form| %>
    <p>
        <%= form.text_field :name, placeholder: "Enter Task Name (required)" %>
    </p><br />

    <p>
        <%= form.text_field :description, placeholder: "Enter Task Description (optional)"%>
    </p><br/>
    <p>
        <%= form.label :due_date, "Due Date (optional)"%><br>
        <%= form.datetime_local_field :due_date %>
    </p><br />

    <p>
        <div class="checkbox-div">
        <%= form.label :completed, "Completed? " %>
        <%= form.check_box :completed %>
        </div>
    </p><br/ >
  
    <p>
    <div class="button">
        <%= form.submit "Submit" %>
    </div> <br>
    </p>

<% end %>

app/views/tasks/completed.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  <div class="main-container">

      <div>
        <h1>💃 Completed Tasks</h1>
        <% if @tasks_completed.length > 0 %>
            <% @tasks_completed.each do |task| %>
                <%= render "task_common", task: task %>
            <% end %>
        <% else %>
            <br />
            <div>You have no task completed.</div>
        <% end  %>
    </div>

  </div>
</div>

app/views/tasks/edit.html.erb
<%= render "layouts/navbar" %>
<div class="spacing">
  <div class="main-container">

    <h1> Edit Task </h1><br />

    <%= render "task_form", task: @task %>

    <br>

    <div class="back-container">
      <div class="bck-btn">
        <%= link_to category_path(@task.category) do %>
          <i class="fa-solid fa-chevron-left fa-xl"></i>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/tasks/new.html.erb
<%= render "layouts/navbar" %>
<div class="spacing">
  <div class="main-container">
    <h1> Add Task for <%= @category.name %> </h1> <br />
    <%= render "task_form", task: Task.new %>

    <div class="back-container">
      <div class="bck-btn">
        <%= link_to category_path(@category) do %>
          <i class="fa-solid fa-chevron-left fa-xl"></i>
        <% end %>
      </div>
    </div>
  
  </div>
</div>

app/views/tasks/overdue.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  <div class="main-container">

    <div>
      <h1>🫢 Overdue Tasks</h1>
      <% if @tasks_overdue.length > 0 %>
        <% @tasks_overdue.each do |task| %>
          <%= render "task_common", task: task %>
        <% end %>
      <% else %>
        <br />
        <div>No overdue tasks.</div>
      <% end  %>
    </div>

  </div>
</div>

app/views/tasks/show.html.erb
<%= render "layouts/navbar" %>
<div class="spacing">
  <div class="main-container">

    <h1><%= @task.name %> </h1>
    <h3>Description: <%= @task.description %> </h3>
    <h3>Due Date: <%= format_datetime(@task.due_date) %> </h3>
    <h3>Completed: <%= @task.completed ? 'Yes' : 'No' %> </h3>
    <br />

    <div class="back-container">
      <div class="bck-btn">
        <%= link_to category_path(@task.category) do %>
          <i class="fa-solid fa-chevron-left fa-xl"></i>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/tasks/today.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  <div class="main-container">

    <div>
      <h1>🍀 Tasks Due Today</h1>
      <% if @tasks_today.length > 0 %>
          <% @tasks_today.each do |task| %>
              <%= render "task_common", task: task %>
          <% end %>
      <% else %>
          <br />
          <div>No tasks due for today.</div>
      <% end  %>
    </div>

  </div>
</div>

app/views/tasks/upcoming.html.erb
<%= render "layouts/navbar" %>

<div class="spacing">
  <div class="main-container">

    <div>
      <h1>🧿 Upcoming Tasks</h1>
      <% if @tasks_upcoming.length > 0 %>
          <% @tasks_upcoming.each do |task| %>
              <%= render "task_common", task: task %>
          <% end %>
      <% else %>
          <br />
          <div>No upcoming tasks.</div>
      <% end  %>
    </div>

  </div>
</div>